# Generated by Django 3.2.9 on 2022-08-25 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('code', models.CharField(max_length=50, verbose_name='Code of Activity')),
                ('sort', models.IntegerField(verbose_name='Order of Activity')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('object_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_process', to='objects.object', verbose_name='object_process')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProcess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
                ('id_record', models.IntegerField(verbose_name='record id ')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start date')),
                ('finish_date', models.DateTimeField(blank=True, null=True, verbose_name='Finish date')),
                ('activity_historical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_historical', to='processes.activity', verbose_name='activity_historical')),
                ('object_historical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_historical', to='objects.object', verbose_name='object_historical')),
                ('process_historical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_historical', to='processes.process', verbose_name='process_historical')),
            ],
            options={
                'verbose_name': 'Historical Process',
                'verbose_name_plural': 'Historical Processes',
            },
        ),
    ]
