# Generated by Django 3.2.9 on 2022-08-05 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Name')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Categoria de Objeto',
                'verbose_name_plural': 'Categorias de Objetos',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la lista')),
                ('native', models.BooleanField(default=False, verbose_name='Is native App')),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'Lists',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Object name')),
                ('description', models.TextField(verbose_name='Object Description')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon')),
                ('view', models.CharField(blank=True, max_length=150, null=True, verbose_name='View')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='Sort')),
                ('model', models.CharField(max_length=150, verbose_name='Model Database')),
                ('visible', models.CharField(blank=True, max_length=50, null=True, verbose_name='Visible')),
                ('representation', models.CharField(blank=True, max_length=150, null=True, verbose_name='Representation Object')),
                ('category_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_object', to='objects.categoryobject', verbose_name='category_object')),
            ],
            options={
                'verbose_name': 'Object',
                'verbose_name_plural': 'Objects',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('description', models.CharField(max_length=150, verbose_name='Description Rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Rols',
            },
        ),
        migrations.CreateModel(
            name='ValueList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('description', models.CharField(max_length=150, verbose_name='Description Value of List')),
                ('code', models.CharField(max_length=50, verbose_name='Code Value of List')),
                ('sort', models.IntegerField(verbose_name='Order Value')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ListValues', to='objects.list', verbose_name='ListValues')),
            ],
            options={
                'verbose_name': 'Value of List',
                'verbose_name_plural': 'Values of List',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('description', models.CharField(max_length=150, verbose_name='Description Relationship')),
                ('visible', models.CharField(blank=True, max_length=50, null=True, verbose_name='Visible')),
                ('object_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_child', to='objects.object', verbose_name='object_child')),
                ('object_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_parent', to='objects.object', verbose_name='object_parent')),
            ],
            options={
                'verbose_name': 'Relation Object',
                'verbose_name_plural': 'Relationship Object',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('visible', models.CharField(blank=True, max_length=50, null=True, verbose_name='Visible')),
                ('add_data', models.CharField(blank=True, max_length=50, null=True, verbose_name='Add Data')),
                ('edit_data', models.CharField(blank=True, max_length=50, null=True, verbose_name='Edit Data')),
                ('delete_data', models.CharField(blank=True, max_length=50, null=True, verbose_name='Delete Data')),
                ('object_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_rol', to='objects.object', verbose_name='object_rol')),
                ('rol_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_permission', to='objects.rol', verbose_name='rol_permission')),
            ],
            options={
                'verbose_name': 'Rol permission',
                'verbose_name_plural': 'Rols permission',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del grupo')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='Sort')),
                ('object_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.object', verbose_name='Objeto')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=150, verbose_name='Field in BD')),
                ('description', models.CharField(max_length=150, verbose_name='Description Field')),
                ('hint', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hint Field')),
                ('type', models.IntegerField(verbose_name='Type')),
                ('type_relation', models.IntegerField(blank=True, null=True, verbose_name='TypeRelation')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='Sort')),
                ('visible', models.CharField(max_length=50, verbose_name='Visible')),
                ('capture', models.CharField(max_length=50, verbose_name='Capture')),
                ('detail', models.CharField(max_length=50, verbose_name='Detail')),
                ('edit', models.CharField(max_length=50, verbose_name='Edit')),
                ('required', models.CharField(max_length=50, verbose_name='Required')),
                ('number_charac', models.IntegerField(blank=True, null=True, verbose_name='Number of characters')),
                ('columns', models.IntegerField(blank=True, null=True, verbose_name='Position in form for columns')),
                ('object_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='objects.object', verbose_name='Object')),
                ('object_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_field', to='objects.group', verbose_name='Group')),
                ('object_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='objects.list', verbose_name='List')),
                ('object_relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationship', to='objects.object', verbose_name='Relationship')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
                'ordering': ['sort'],
            },
        ),
        migrations.AddConstraint(
            model_name='valuelist',
            constraint=models.UniqueConstraint(fields=('code', 'list'), name='unique ValueList'),
        ),
    ]
