# Generated by Django 3.2.9 on 2022-01-17 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='Description')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='objects/', verbose_name='Imagen de Categoria Objetos')),
            ],
            options={
                'verbose_name': 'Categoria de Objeto',
                'verbose_name_plural': 'Categorias de Objetos',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la lista')),
                ('native', models.BooleanField(default=False, verbose_name='Is native App')),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'Lists',
            },
        ),
        migrations.CreateModel(
            name='ValueList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('description', models.CharField(max_length=150, verbose_name='Description Value of List')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code Value of List')),
                ('order', models.IntegerField(verbose_name='Order Value')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ListValues', to='objects.list', verbose_name='ListValues')),
            ],
            options={
                'verbose_name': 'Value of List',
                'verbose_name_plural': 'Values of List',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Object name')),
                ('description', models.TextField(verbose_name='Object Description')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon')),
                ('view', models.CharField(blank=True, max_length=150, null=True, verbose_name='View')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Order')),
                ('model', models.CharField(max_length=150, unique=True, verbose_name='Model Database')),
                ('category_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.categoryobject', verbose_name='Categoria de Objeto')),
            ],
            options={
                'verbose_name': 'Object',
                'verbose_name_plural': 'Objects',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre del grupo')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Order')),
                ('object_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.object', verbose_name='Objeto')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Field in BD')),
                ('description', models.CharField(max_length=150, verbose_name='Description Field')),
                ('hint', models.CharField(max_length=200, verbose_name='Hint Field')),
                ('type', models.IntegerField(verbose_name='Type')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Order')),
                ('visible', models.CharField(max_length=50, verbose_name='Visible')),
                ('capture', models.CharField(max_length=50, verbose_name='Capture')),
                ('required', models.CharField(max_length=50, verbose_name='Required')),
                ('number_charac', models.IntegerField(blank=True, null=True, verbose_name='Number of characters')),
                ('columns', models.IntegerField(blank=True, null=True, verbose_name='Position in form for columns')),
                ('object_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='objects.object', verbose_name='Object')),
                ('object_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='objects.group', verbose_name='Group')),
                ('object_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='objects.list', verbose_name='List')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
            },
        ),
        migrations.AddConstraint(
            model_name='valuelist',
            constraint=models.UniqueConstraint(fields=('code', 'list'), name='unique ValueList'),
        ),
    ]
